package util

const (
	RoleKey                  string = "ROLE#"
	SuperAdminKey            string = "SUPER_ADMIN#"
	TenantKey                string = "TENANT#"
	HospitalKey              string = "HOSPITAL#"
	DoctorKey                string = "DOCTOR#"
	ReceptionistKey          string = "RECEPTIONIST#"
	NurseKey                 string = "NURSE#"
	PharamacistKey           string = "PHARMACIST#"
	PatientKey               string = "PATIENT#"
	MedicinesKey             string = "MEDICINES#"
	MedicalRecordKey         string = "MEDICAL_RECORD#"
	AppointmentKey           string = "APPOINTMENT#"
	PrescriptionKey          string = "PRESCRIPTION#"
	TestKey                  string = "TEST#"
	TestReportKey            string = "TEST_REPORT#"
	BillKey                  string = "BILL#"
	GuardianKey              string = "GUARDIAN#"
	SuperAdminCollection            = "SUPERADMIN"
	TenantCollection                = "TENANT"
	HospitalCollection              = "HOSPITAL"
	DoctorCollection                = "DOCTOR"
	DoctorTimeSlotCollection        = "DOCTOR_TIMESLOTS"
	ReceptionistCollection          = "RECEPTIONIST"
	PatientCollection               = "PATIENT"
	MedicalRecordCollection         = "MEDICAL_RECORD"
	NurseCollection                 = "NURSE"
	MedicineCollection              = "MEDICINES"
	AppointmentCollection           = "APPOINTMENT"
	TestReportCollection            = "TEST_REPORT"
	TestCollection                  = "TEST"
	PharmacistCollection            = "PHARMACIST"
	PrescriptionCollection          = "PRESCRIPTION"
	RoleCollection                  = "ROLE"
	BillCollection                  = "BILL"
	GuardianCollection              = "GUARDIAN"
)
